x = input('Digite alguma coisa: ')
print(f'Tipo primitivo: {type(x)}')
print(f'Somente espaços? {x.isspace()}')
print(f'É número? {x.isnumeric()}')
print(f'Somente letras? {x.isalpha()}')
print(f'Somente letras e números? {x.isalnum()}')
print(f'Somente maiúsculas? {x.isupper()}')
print(f'Somente minúsculas? {x.islower()}')
print(f'Capitalizada? {x.istitle()}')
